### ISSUE TITLE
BUG: Doesn't work with patreon only version

### ISSUE THREAD

**Issue by Jonwh25** [otigon/automated-jb2a-animations#1]
If you have the Patreon only version there is no need for the "Free" version to be installed. The dependency the module requires makes it so you have to have the free version installed for this to work.

**Comment by hwfwalton** [comment]
Just ran into this as well.
It's a false warning. The . It's just that this module lists the free asset pack in the `dependencies` of it's `module.json`.
It is fine to just leave both the free and Patreon versions activated to keep this dependency happy.

That said, I totally resonate with wanting to uninstall the free version to declutter ones modules list. To work around this, I manually edited the `module.json`  of my local copy of `automated-jb2a-animations`.  I found the file at:
`C:\Users\<user>\AppData\Local\FoundryVTT\Data\modules\automated-jb2a-animations`
One can either remove the dependency listing for `JB2A_DnD5e` entirely, or update it to check for `jb2a_patreon`.

This "fix" is likely very brittle, but it at least lets one uninstall the duplicate module 🤷‍♂️

**Comment by otigon** [comment]
I'm looking for a better work around rather than having the Free module as a dependency. That's in place so someone doesn't install the module and simply have it not work (not checking that JB2A is required). It will work with either, and takes preference to the Patreon module when that is installed.

**Comment by otigon** [comment]
> If you have the Patreon only version there is no need for the "Free" version to be installed. The dependency the module requires makes it so you have to have the free version installed for this to work.

I'm looking for a better work around rather than having the Free module as a dependency. That's in place so someone doesn't install the module and simply have it not work (not checking that JB2A is required). It will work with either, and takes preference to the Patreon module when that is installed. However, for now it will require the Free version to be installed/active.

You can use the method hwfwalton used, and simply remove that from the module json locally.

**Comment by otigon** [comment]
I'll be removing the dependency for requiring the Free JB2A module to be installed and active. I'll be adding plenty of error messages if neither module is installed, and a new pop-up window on update to let people know they need at least one of the 2 JB2A modules for this to work
