### ISSUE TITLE
Why pf2e is not being worked on anymore?

### ISSUE THREAD

**Issue by Ghilteras** [otigon/automated-jb2a-animations#110]
```
Systems in Process for Compatibility:

Starfinder (in process)
Warhammer (awaiting 0.8 system release)
DnD 3.5 (in process)
Please log a GitHub request for other systems
```
Why did you guys stop working on pf2e?

**Comment by otigon** [comment]
PF2e, as it is right now, cannot be reliably supported due to how the Item data is parsed to create attacks/spells on the character sheet. I'm told they are revamping that entire item system right now, and the next update should allow for integration with Automated Animations. I think they're pushing to have that out sometime around August

**Comment by Ghilteras** [comment]
@otigon the next update landed, did this got resolved?

**Comment by otigon** [comment]
I asked the dev who worked on this, they're doing a big content release in the next few days and this feature should come in the update after that, so sometime soon
