### ISSUE TITLE
[FEATURE REQUEST] Allow animations on self without targeting

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#113]
Hello,

Can you make it so the Bardic Inspiration and other animations that have an option to play on self, plays the animation even without target(s)? Just like healing animations.

**Comment by otigon** [comment]
Bardic Inspiration already has this feature that  you can choose to animate on Target and/or Self. For some, like healing spells, this is also the case if there is no target.

What other cases were you envisioning? (I don't want to implement this for ranged attacks because then it get messy/ugly with animations firing off in random directions)

**Comment by DarKDinDoN** [comment]
@otigon Hmmm, ok. Maybe a bug then?
Cause when I'm trying bardic inspiration without targets, I don't get any animation, Even tho the "self" checkbox is ticked.

**Comment by otigon** [comment]
I'll give it a check, that shouldn't happen like that

**Comment by otigon** [comment]
Bardic Inspiration should be fixed to play on self if no targets are selected
