### ISSUE TITLE
Animated Weapon Drifts

### ISSUE THREAD

**Issue by chroot** [otigon/automated-jb2a-animations#12]
Thank you so much for your work on this.  My players love these effects but historically hate making it work; as we start our new campaign this should be a great treat for them.  I'm running into an odd issue; my attack sequence goes as follows

1. Target baddie
2. Select my token
3. Use the HUD/Character Sheet/* to start the attack
4. Roll damage and watch the animation

However all animations start about 2 squares behind my token and as they take their action the drift back another 10.  I've attempted as many variations of launching the attacks as I can think of but it still happens.  I'm sure this is just me being foolish but I felt it best to post this.  

This is not isolated to this player, nor this game.  Enabling this module in other games has the same effect.  

Any assistance or guidance would be appreciated.

General Info:
Foundry Version:
   - 0.7.9
 
OS:
   - CentOS 8
   
Active Modules: 57
   - https://photos.app.goo.gl/CgB57UmzeMddxFNn9

Video of it occurring: 
   - https://photos.app.goo.gl/MtBMrsh6kAxT2feX6

**Comment by otigon** [comment]
Hey @chroot , this is an issue between FX Master (which I use to play the animations) and the About Face module. If you are comfortable with modifying javascript, there is a (fairly) simple fix I can provide, otherwise you would need to disable the About Face module.

The FX Master author is aware of this, but I'm not certain when they will be able to get around to updating with the fix

**Comment by chroot** [comment]
I'll remove about-face.  The edit wouldn't be an issue, I just know I'll forget it next time that mod updates.  Thank you for all of your help and for writing this.

**Comment by otigon** [comment]
No problem, I'll keep an eye out for FX Master on their next update to see if they put their fix in
