### ISSUE TITLE
[BUG] Preview not updating when changing spell color

### ISSUE THREAD

**Issue by kuchrk24** [otigon/automated-jb2a-animations#150]
Foundry v0.8.8
Automated Animations v0.5.03
JB2A - Patreon Complete Edition v0.2.3

Preview does not update but it does use the correct color in game.
![aniamtion preview](https://user-images.githubusercontent.com/74018852/127027683-255f9708-0112-400b-ba85-c357bb0344fe.gif)

**Comment by otigon** [comment]
The preview you see on that page is for the Automatic Recognition only, so that would be the Purple animation. You wouldn't see the color changes unless you were inside the Customization settings. I'll take a look and see about updating to reflect color changes as well for the automatically recognized preview

**Comment by kuchrk24** [comment]
Ah, no worries. I've only been playing around with it for a couple hours so I probably missed where that was stated. Thanks.

**Comment by otigon** [comment]
I'm going to close this issue out. The 0.6.0 release (this weekend), will be implementing a reworked automatic recognition system that is defined by the GM via an interface in the Module settings. The color will still be able to change on the items, and the video preview will update in those instances.
