### ISSUE TITLE
Question regarding animation only on attack and bug report.

### ISSUE THREAD

**Issue by nulmas** [otigon/automated-jb2a-animations#20]
Hey! First of all, congratulations on a great mod.

I'm using midi-qol, and I'd like for the animation to play when the players attack and not when they roll damage (they're doing separate rolls). Is there any way to do this or any plan to implement it in the future? 

Another issue: at first, I thought the animation was only playing when rolling for damage, regardless of if that option was activated. After some testing, I realized what was happening: there's a bug. If the option to only play the animation when the attack hits is on, the animation will only play when rolling damage. But if it's off, it will play when rolling for damage and when the attack **misses**, but not when it hits.

**Comment by otigon** [comment]
For the 2nd issue, this is as intended by the way Midi-QOL determines if the workflow is completed. You are checking for hits in the Midi Workflow settings, and on a miss the workflow is considered complete. The animation will play at that time, otherwise it will play on damage. If you weren't checking for hits with Midi, it would always play on the Damage Roll.

On the first subject, I'll get with Tposney to see if there is a way he can pass when the attack roll is made. If we can swing that, I'll have that as the default.

**Comment by nulmas** [comment]
Ah, I understand. In retrospect, I should have realized what was going on: since the attack resolves when the damage is rolled, that's when the animation plays on a hit.

Thank you! 

PS: Maybe you should mention that on the readme to avoid this being brought up again.

**Comment by otigon** [comment]
Good point lol. I'll update the ReadMe this morning
