### ISSUE TITLE
Better Automatic Recognition

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#216]
Hello,

Awesome update with 0.6.0!

Assuming a default animation named "Sword".
Do you think it could detect the item "Fire sword" and default to this animation?

All we have to do then, is to click the "Override Automatic Setting" checkbox and change the color to "Yellow" and BAM we have a "Fire sword" animation in no time! :)

**Comment by otigon** [comment]
I have to consider too many systems to do that

**Comment by DarKDinDoN** [comment]
@otigon Hey, ok.
I fail to understand why it's system dependent.

I was thinking, instead of a struct comparison like this: https://github.com/otigon/automated-jb2a-animations/blob/6ce94173257479f2bc03cc9c8778630efb370f86/src/custom-recognition/autoFunctions.js#L27

Maybe something like:
`if (newName.includes(currentArrayName)) {`

With this:
- "Sword" includes "sword"
- "Fire sword" includes "sword"

Now, I reckon that's not a perfect solution. Because it might be possible that "Greatsword" includes "Sword" as well.

Would you be open to a PR for that?

**Comment by otigon** [comment]
Well, consider that it would take me several hours of work to implement all the checks and balances, when you can spend 3 minutes to set the spell up in auto-recognition. so no

**Comment by otigon** [comment]
To add a little more insight to this, I opted not to use any includes() method because you run the risk of stepping on names of not just other items in the game world, but item names I'm other systems.

If someone wants to build out system specific methods to run the name checks, I'm all ears and would be open to a PR for that, but it's not something that I will be putting effort into
