### ISSUE TITLE
Multi name 

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#247]
Hi,

Can you make possible to add multiples names to an animation pattern?

Maybe comma or ;, or something else

![image](https://user-images.githubusercontent.com/4999783/134787188-761dcb46-97c8-457e-addb-901856d4d852.png)

**Comment by otigon** [comment]
Hey, I had two choices to make when I upgraded the automatic recognition menu. I could use the comma method, or an includes(). Both together are a bit much to maintain. I chose includes() so that a single word could grab multiple item types (sword = longsword, shortsword, shortsword +1, etc. 

I'll take a look and see how horrific it would be to add that, but can't promise anything

**Comment by otigon** [comment]
Not going to be adding this feature
