### ISSUE TITLE
Request: Compatibility for the Dark Heresy 2E System

### ISSUE THREAD

**Issue by Waschko** [otigon/automated-jb2a-animations#317]
I love A-A and it would be a great addition to any gameplay in the Warhammer 40k setting.
Link to the System: https://github.com/moo-man/DarkHeresy2E-FoundryVTT

EDIT: I just read your post regarding your work on Compatibility ... missed that at first

**Comment by otigon** [comment]
In order to add support, the game system needs to pass certain data either through the "createChatMessage" hook when an Item is used, or by system specific hooks. I checked and this system doesn't pass any of it unfortunately. Namely, Token/Token ID, Item/ItemID/ItemUUID, etc. 

You could log an request with the System administrators to add some reference to the Token using the item, and some reference to the Item (Item Document, ID or UUID). Beyond that there isn't anything possible for me to do sorry.
