### ISSUE TITLE
Feature Request: Animations tied to PF2E effects

### ISSUE THREAD

**Issue by akinokaze** [otigon/automated-jb2a-animations#337]
In the PF2E system, effects for persistent damage like bleed and spells like shield handle the automation of dealing damage/buffs/debuffs. They also time out when the effect expires or is removed. These are treated as items in Foundry core.

It would be neat if AA could tie animations to these effects so removing them is handled by the system itself (when the effect is removed by time/cleansing/death/whatever).

Currently you can see the AA menu on these items, but they don't seem to trigger when the effect is added to a token.

**Comment by Iankid** [comment]
This for Starfinder as well

**Comment by Joshmvii7** [comment]
Just leaving a comment to note that this would be incredibly desirable for any PF2E game that uses AA.

**Comment by otigon** [comment]
Yeah it's on my list next to look at. I need to dig into the PF2e effects to see how they work

**Comment by MrVauxs** [comment]
Looking forward to this feature as well!

**Comment by otigon** [comment]
So it looks like whatever system/methods PF2e is using for these items is not tied to Foundry's active effect system. There is also no way for me to test this because I don't know the system at all, and I don't have the time to learn how to set it up and get it working to even be able to test.

Thus, I won't be able to add any support for this. My work on the module is winding down as I only have a few more updates before I stop actively working on new features and only perform periodic maintenance.
