### ISSUE TITLE
PF2e troublesome Items

### ISSUE THREAD

**Issue by otigon** [otigon/automated-jb2a-animations#387]
Log of items for PF2e that don't play nice

**Comment by SacredDenizen** [comment]
"Ray of Enfeeblement" 1st Level spell. Plays the animation when settings are default but will not play the animation when settings are set to play on damage rolls. Assuming it is because this spell has an attack roll but no damage roll since it only applies debuffs and has no damage component.

**Comment by MrVauxs** [comment]
Concordant Choir, Heal, Harm, Gravitational Pull, and Rip the Spirit are all spells in the PF2e system that have variable casting times, changing their targeting and thus, animations with the amount of actions used. Pretty much all of them follow the schema of:
- 1 action = touch
- 2 action = ranged and more damage / healing
- 3 action = 30-foot or more burst, which requires a template

Heal Animal, Heal Companion also have such variable casting times, but do not have the 3rd action burst.

The issue here is that you can only apply 1 animation to one item/spell/effect, while this requires multiple. Currently, only the 1 action version of the animation works. While we could ignore the 2 action version as it is almost the same as the 1st one, some (and most likely gonna be all spells by the end of the day) use `[[/r ]]` commands to do the second action effects, skipping over the animations.
The main issue is the third action template, as you cannot have say, the Heal spell, simultaneously be an "On Token" animation and a "Template" animation, or at least that's how the PF2e integration works. AA seems to prefer the On Token animation in this specific instance.

**Comment by MrVauxs** [comment]
Stabilize. It's a Healing spell without any healing rolls, this most likely being the reason why the animation doesn't go off.

**Comment by tyrielv** [comment]
Raise a Shield. It plays the default animation which is intended for Shield spell.

**Comment by MrVauxs** [comment]
> Raise a Shield. It plays the default animation which is intended for Shield spell.

This isn't a troublesome item. Make a separate entry for Raise a Shield and the problem will subside. If anything contains the word Shield, it will go for the Shield animation, unless there is a longer match.

**Comment by tyrielv** [comment]
Thanks, I didn't realize that was an option

**Comment by MrVauxs** [comment]
Black Tentacles, Heal, and various other spells would benefit from the ability to have both `Template` and `On Token` animations at once, depending on what you just did (roll an attack roll / place a template). `On Token` should be possible to use multiple times, much like any other attack rolls.

**Comment by otigon** [comment]
Going to officially close this Issue since I've released the System workflow refactors for A-A version 4+. I verified that all the items listed in here work as expected now
