### ISSUE TITLE
Feature Request: Option to toggle on target effects from Starfinder system

### ISSUE THREAD

**Issue by JonDemand** [otigon/automated-jb2a-animations#404]
i was looking for a way to set a marker on a token when a skill is toggled on,  and then remove the marker when the skill is deactivated.

Persistent doesn't work as it just leaves the marker on the token forever,  even after the skill is toggled,  currently doing it with repeats for x time but would like a tidier solution and was asked to log it on here as a request

**Comment by otigon** [comment]
Are there any default actors I can test with that have toggleable skills already set up? Or, can you point me in the direction of where/how to add one of these toggleable skills?

**Comment by otigon** [comment]
I see the "modifiers" tab and can confirm those are utilizing the Active Effect system (will be able to add support for those). I'll wait to hear back on the above mentioned task before proceeding

**Comment by JonDemand** [comment]
There is a Characters compendium,,  Navasi L1/L4/L8 should all have Get 'Em,  which is the one i was trying to do

**Comment by otigon** [comment]
<img width="365" alt="image" src="https://user-images.githubusercontent.com/73318661/167275935-c17e1035-c58b-4789-9951-f8ea135473ea.png">
These in the Features tab?

**Comment by JonDemand** [comment]
yeah,  actually both of those could work with a marker to say something is applying to the target

**Comment by otigon** [comment]
Starfinder is nice enough to provide Hooks for when those are toggled. I should def be able to add support for those too.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/73318661/167275997-04a82d7d-8e7c-4816-b71d-9586d012dd40.png">

**Comment by JonDemand** [comment]
Great news :)

**Comment by otigon** [comment]
I was going to wait until the new major release to get this done, but it is taking longer than expected. So, I should have support for Active Effects in SFrpg released tomorrow. 

The Modifiers page will function off of the Active Effects tab in the Autorec Menu since those are static effects. Items on the Features Tab of the character sheet are not Active Effects, so those will still be handled through the normal Autorec menu options, or defined on the item themselves. If they have a togglable effect the animation will be triggered on that use. And, if it is a ``persistent`` effect, it will remove itself when the Feature is deativated/expires

**Comment by otigon** [comment]
Added support for Starfinder Active Effects and togglable Feats in version 3.2.2

**Comment by otigon** [comment]
reopening due to release issues

**Comment by otigon** [comment]
active on v 3.2.8
