### ISSUE TITLE
Explosion selection missing variant selections.

### ISSUE THREAD

**Issue by Iankid** [otigon/automated-jb2a-animations#465]
Because there are now more variations in explosions, with the only variation option explosions being 01, the animation is random what explosion happens.

**Comment by otigon** [comment]
This was intentional when creating the A-A database for the animations, the shear volume of "explosions" made it easier to just randomize them by color. I'll leave this open as consideration for modifying the database to allow individual selections, but in the meantime the only way would be to select custom animations for them
