### ISSUE TITLE
AA triggers macros of templates when PF2 effects are applied/removed

### ISSUE THREAD

**Issue by apoapostolov** [otigon/automated-jb2a-animations#502]
I am working with a dev to develop a PF2 mod that adds PF2 effects when a token is in dim light or darkness. What the mod does is apply effects that are named "Dimly Lit" and "In Darkness" and removing them when moving into a different lighting state.

Using AA, JB2A x PF2, I ran into an advanced macro error that took a lot of time to debug where the issue comes from, and we found out that the issue is that when "In Darkness" effect is removed, an AA preset for the template called Darkness is triggered, which in JB2AxPF2 is set to the macro Compendium.pf2e-jb2a-macros.Macros.Darkness

![image](https://user-images.githubusercontent.com/4083812/195124546-fab3ea8b-4bbb-4cb7-909e-cec16d9cf701.png)

This makes it impossible to use PF2 effects with the word "Darkness" in it and forcing us to rename our effect to work as is, but isn't this a template trigger, why does it affect effects?

**Comment by otigon** [comment]
The Global Automatic Recognition menu in A-A is done entirely on name comparison, and does not do exact matches. So in this instance that Darkness entry would always que off anything with Darkness in the name. Normally this wouldn't be an issue for you, except that PF2e doesn't utilize the core Active Effect system, instead everything is an Item which effectively tries to use the entire Autorec menu.

Originally "effects" would only check against the Active Effect menu, but due to Rule Element strikes and such the PF2e workflow got changed to treat everything the same so the PF2e x JB2A module could latch on and apply animations as they wanted.

I do plan on revamping the PF2e workflow at a later date, but that will be several weeks before I can get to it. I'm uncertain how to fix this in the current workflow. It might be possible for you to add a Flag on those effects that A-A can look for, and exit out of the workflow accordingly. That would probably be the simplest solution

**Comment by otigon** [comment]
So in this instance as an example, when you apply the effect I can have A-A look for:
``item.flags.pf2e.shouldIgnore`` (or whatever you think the flag path and name should be, doesn't matter). This would allow me something to stop the A-A workflow so it wouldn't be throwing errors or unintended animations

**Comment by apoapostolov** [comment]
@otigon Having a ignore flag could be very useful. I will check with the dev what would be the best technical solution.

Alternatively, is it something that can be added to the effect A-A options? Or you were already talking about something that can be added to that menu?

![image](https://user-images.githubusercontent.com/4083812/195148405-acf9c594-6e4c-41dc-8f66-2a0395eaccd6.png)

**Comment by otigon** [comment]
Come to think of it you could create the A-A flags on the item using:
``item.flags.autoanimations.isEnabled: false``
That's also an easy check on my end that would exit out the workflow. (I need to add that check in anyway on my next release)

**Comment by apoapostolov** [comment]
Thanks, I will pass this to the dev so we edit our effects supplied with the mod.

**Comment by otigon** [comment]
I had to push out an update a little early. This check is active as of version 4.0.06. Feel free to reach out on Discord as well if anything else pops up
