### ISSUE TITLE
Color selection is missing for some of the spells with localized names

### ISSUE THREAD

**Issue by ZwS** [otigon/automated-jb2a-animations#52]
For following spells `AnimateItem#meleeColor()` method doens't work properly since there is no check for localized name.

* call lightning
* sleetstorm
* spirit guardians
* wall of force
* whirlwind
* darkness
* hunter's mark
* bardic inspiration
* guiding bolt

**Comment by otigon** [comment]
I must have forgot to add the localization. I'll check it out and get it fixed

**Comment by otigon** [comment]
This should be fixed as of 0.3.20 so long as the localization is filled out for those (some haven't been  updated for a while)

**Comment by elbracht** [comment]
@otigon I think I have a similar problem. The animations are not assigned to the above spells. Neither with the original name nor with the translation.

I use the following versions

Automated Animation: 0.5.28
JB2A: 0.2.4.3

![image](https://user-images.githubusercontent.com/2912000/129566380-5d583c92-f3bf-4714-8f8c-cf18cceb5b92.png)

**Comment by otigon** [comment]
Hunters Mark an those listed above are not automatically recognized, so the color options will not populate. You need to manually set those up.

I will be reworking the Automatic Recognition system next month to allow users to set their own via the module settings, so that will help in this instance
