### ISSUE TITLE
`Await Animation Completion` macro option

### ISSUE THREAD

**Issue by MrVauxs** [otigon/automated-jb2a-animations#530]
It would be nice to have a "Await Animation Completion" option for the macro, with it also integrating with wait/delay attributes.
Very useful for ex. summoning, where you have the token at first Invisible, and then want them to be visible, so you make the animation of revealing them and say 500 ms before finishing a macro is ran to make their opacity 100%.
Or just anything you want to do animation first, code second.

**Comment by otigon** [comment]
For this option, it would have to be call outside of the Sequence (since the Sequence is ``await``ed, so Wait won't be of much use. However, things run immediately after the last Sequence section is called, so 99% of the time you'll want the ``Delay`` (I.E. the macro would run as soon as the last Sequence section is started, not after the animation has played)

**Comment by otigon** [comment]
Also might even be best to leave any Delay to be called inside the Macro, and you can pass that variable thru the Args

**Comment by MrVauxs** [comment]
> For this option, it would have to be call outside of the Sequence (since the Sequence is `await`ed, so Wait won't be of much use.)
Why? Can't the macro just be added at the end through `.thenDo()`?

**Comment by otigon** [comment]
I'll test it out with ``thenDo.()`` first, but I seem to recall it doing something like that yeah

**Comment by otigon** [comment]
Fixed on version 4.0.22
