### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BlackWand1** [otigon/automated-jb2a-animations#88]
Awesome initiative to develop this module.

Just some suggestions:

1. Add "custom" option where the user can browse to animation and set options for self, target, direction, rotation etc so that we can utilize all the animations in JB2A and not be limited to the, like, 7, spell attacks.
2. Button for "test animation" should animate on the canvas, to verify/test the options set in 1.
3. Maybe have the option to repeat the animation according to the number of attacks that the player choses (according to BaB/haste etc). This value should be able to retrieve from chat/foundry?

I bought JB2A and was expecting to have the option for more animations - but that was not the case :(

**Comment by otigon** [comment]
Which animations are missing from what you were expecting in the JB2A module?

**Comment by BlackWand1** [comment]
For attack spells, as an example, ibwas expecting more ready to use animations.
I had like 7 to 10 spells to pick from. Is that all there is in the A.A module today?

I am running foundry 7.10 so maybe i need to go to version 8 to get updated A.A module?

Robert Winbladh

________________________________

**Comment by otigon** [comment]
Using Attack Spells as an example, I'm limited to what is available in the JB2A module as I have not incorporated any other animation modules into Automated Animations yet. There is auto-recognition for certain spells that have an animation available by JB2A such as Fire Bolt, Guiding Bolt, Disintegrate, etc. I have not tied any into others because you can customize any spell you wish to by using the A-A Tab and setting Overrides for animations/colors.

That being said, I have incorporated every single Attack Spell, Ranged Attack and Melee Attack available in JB2A, and have been branching off to add explosive effects, template options, etc. For the purpose of this module (instant effects) I have probably incorporated 95% of what is available in JB2A in that area, and even used others for persistent effects when combined with the Custom Token Animations module by Kandashi.

The module is entirely backwards compatible with 0.7.9 Foundry and above, so you don't need to upgrade to get "new" effects. And, I'm constantly updating to add new release JB2A animations.

Beyond that, I'm not entirely certain what else you were expecting?

For the other points above:

1. I like the idea of a custom option that would provide that kind of detail and user selectable animations for that. I'll def put that on the list but it will take some time to implement.

2. I don't like the idea of putting the work in for adding a test button when you can just use the item from the sheet to test it.

3. A "loop" option is planed for implementation across the board, but requires some reworking of code to get it implement smoothly

**Comment by BlackWand1** [comment]
Ok. When doing override animation, the list i get then is rather limited. Is the full functionality only when not overriding?


Maybe i can get you a screenshot later.

Robert Winbladh

________________________________

**Comment by otigon** [comment]
Yeah send me a screen shot. I also updated the ReadMe on the GitHub page so check that and make sure you have all those options. If you upgraded from version 0.3.28 to 0.3.50 or above, make sure you uninstalled the module before updating, as I had to change some things on the module side that required an uninstall/reinstall

**Comment by BlackWand1** [comment]
That is all there is for attack spellls when i override.

[Image]


Robert Winbladh
________________________________

**Comment by otigon** [comment]
Not able to get pictures to come through, but if you want to reach out on the JB2A discord you can send some stuff there

**Comment by DarKDinDoN** [comment]
@otigon Hi,
Expanding on that.
JB2A patron module offers a loooooot of animations, not only attacks, but generic animations as well (Ui, smoke, items, etc.).
I really like the idea of having a way to set up a custom animation regardless of the type of item being used.

This way, we could get some cool animations that the module does not provide in the configuration window.

**Comment by otigon** [comment]
Keep an eye out for the 0.5.0 release tomorrow, this feature is being implemented

**Comment by otigon** [comment]
Release is live now
