### ISSUE TITLE
System Request - PF2e

### ISSUE THREAD

**Issue by netavarka** [otigon/automated-jb2a-animations#98]
Please add support for Pathfinder 2e to the module.
I would really love to see fireballs flying around.

Thanks a lot!

**Comment by otigon** [comment]
I took a look again, and unfortunately they still don't tie anything to the item when you roll stuff. A-A needs to grab the item flag data, and since the PF2 system is coded wildly different from just about any other system, there is no way for me to get the information my module needs to get animations to play. Sorry

**Comment by Bolt7** [comment]
I've talked to the 2e devs (I'm not one) and animation module compatability is a planned thing for the spell system overhaul this summer. You'd still have to do it, but it should be possible soon™. Just wanted to give a heads up.

**Comment by netavarka** [comment]
Thank you for looking into it.
Guess i will read all the PF2e release notes now ;-)
